services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
  authelia:
    image: authelia/authelia:4.38.8
    volumes:
      - "{{ environ('LOCAL_WORKSPACE_FOLDER') }}/test/authelia_configuration.rj2.yml:/config/configuration.yml"
      - "{{ environ('LOCAL_WORKSPACE_FOLDER') }}/test/authelia_users.rj2.yml:/config/users.yml"
  token-handler:
    environment:
      BASE_PATH: /auth
      IDENTITY_PROVIDER_BASE_PATH: https://authelia.auth-tools.home
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    build:
      context: ./token_handler
      dockerfile: Dockerfile
    extra_hosts:
      - "authelia.auth-tools.home:172.16.238.10"
    volumes:
      - "{{ environ('LOCAL_WORKSPACE_FOLDER') }}/test/token_handler_configuration.yml:/config/clients.yml"
  proxy:
    image: traefik:v2.11.2
    networks:
      default:
        ipv4_address: 172.16.238.10
    volumes:
      - "{{ environ('LOCAL_WORKSPACE_FOLDER') }}/test/traefik_static_conf.yml:/etc/traefik/traefik.yml"
      - "{{ environ('LOCAL_WORKSPACE_FOLDER') }}/test/traefik_dynamic_conf.yml:/etc/traefik/traefik.dynamic.yml"
networks:
  default:
    name: auth-tools
    external: true
